SFML/imgui-sfml

- imgui-SFML.cpp
- imgui-SFML.h
Maybe you are interested in my changes:
I have added sfml overloads for ImageButton (does not work otherwise for me).
Some other minor modifications, notable: If using ImGui::Image with only a sf::Sprite the the size of the sprite is taken (e.g. is uses now the scale of the sprite) I think for sprites this is more logical, for sf::Textures everything stays like it is.
> Added sf::Sprite and sf::Texture overload for ImageButton

- imgui-SFML.cpp
Use abs on the size vector before passing it onwards for when given a texture rect with negative width and/or height.
That way, when you want to draw an image with 'flipped' texture coordinates, it won't end up to the left of where it ought to be, or above (ImGui::Image moves the 'cursor' by the size it is given, and draws from where it was to where it now is).
> Update Image(texture, textureRect...)

- imgui-SFML.cpp
In the new version of ImGui the function ImGui::Shutdown() is private. That function is been replaced with ImGui::DestroyContext() and  ImGui::CreateContext() is been called in the ImGui::FSML::Init() function..
> Fix issue #44

- README.md
Includes a method to fix the issue on macOS. I'm not sure what solution to suggest for high DPI screens on other platforms.
I'll grab a screenshot of the issue for your blog post, but figured it's not worth adding to the README here?
> Add README section about high DPI screens

- imgui-SFML.cpp
Fixes this warning:
```
imgui.h(132): warning C4244: 'argument': conversion from 'const float' to 'int', possible loss of data
imgui-sfml.cpp(338): note: see reference to function template instantiation 'ImVec2::operator sf::Vector2<int>(void) const<int>' being compiled
```
> Fix implicit cast warning

- imgui-SFML.cpp
`ImGui::Image(...)` isn't rendering `sf::Sprite` with `textureRect`.
> Fixed bug with textureRect in Image widget

- imgui-SFML.cpp
Add supression of warnings (caused by converting from uint to void* in pCmd->TextureID) for Microsoft's compiler. Supression only worked for Clang and GCC.
> Add supression of warnings for Microsoft's compiler

- CMakeLists.txt
This piece of code was left in 90d895b8069d35a192b1da664237ce30741299f1, and it causes an error in a fresh build:
```
CMake Error at CMakeLists.txt:48 (cmake_policy):
cmake_policy POP without matching PUSH
```
> Remove cmake_policy POP

- imgui-SFML.cpp
Imgui uses UTF-8 for the internal representation of its strings. On the other side SFML uses UTF-32 in its `sf::String`.
The problem is when the `toAnsiString` method is called, the comportment of this method is to discard chars that don't fit in the current encoding (`std::locale()`), so if you copy/paste a non-ansi char (for example ひ), it doesn't work.
To address this problem I used the `toUtf8` method that convert the UTF-32 string to an UTF-8 one.
An other solution to fix this problem is to convert `s_clipboardText` to a `std::basic_string<unsigned char>` and to use the following code: 
```cpp
const char* getClipboadText(void* /*userData*/) {
s_clipboardText = sf::Clipboard::getString().toUtf8();
return reinterpret_cast<const char*>(s_clipboardText.c_str());
}
```
But I am not sure …
> Fix clipboard for unicode strings

- imgui-SFML.cpp
ImGUI uses the io.KeySuper instead of Ctrl on macOS for shortcuts, but there isn't an implementation on how KeySuper is setted, so doing any shortcut does nothing. This PR fixes that.
> Added KeySuper update (fixes the inability to use shortcuts on macOS)

- imgui-SFML.cpp
This is what this pr changes:
- Removed the char filter under 0x10000 (it's no more needed after [this commit](https://github.com/ocornut/imgui/commit/ef13d95466f27b4a955d6f95da90822001ace25f))
- Removed the cast to ImWchar (it's no more needed after the commit linked above)
- Added a filter to \n (line feed), \r (carriage return), \t (tab) and \b (backspace) which are all handled inside ImGui (fixes the double linefeed bug in macOS #91)
> Filter some characters that imgui already handles

- CMakeLists.txt
Just notices while installing that the error message complains about IMGUI_ROOT not being set while the script actually checks for IMGUI_DIR.
Cheers and keep up the good work!
> Correct error message regarding IMGUI_DIR

- CMakeLists.txt
I was trying to use CMake to compile ImGui-SFML but it was complaining that it couldn't find it, and I deduced that it was because my SFML libraries are built as static libs. Added this to make it work and thought I'd share.
> Add option to use static SFML libraries to CMakeLists

- examples/main.cpp
According to the imgui changelog v1.53 of imgui deprecated `SFML::ShowTestWindow`. It kept the function around for a while until v1.75 which removed the reference. This means that compiling with `IMGUI_SFML_BUILD_EXAMPLES=ON` fails with the most recent of SFML.
I've adjusted the main.cpp to use `SFML::ShowDemoWindow`
> Rename SFML::ShowTestWindow to SFML::ShowDemoWindow

- CMakeLists.txt
- README.md
Enabling it will result in compiling imgui_demo.cpp file, that contains e.g. ImGui::ShowDemoWindow function, which is useful for new users.
Resolves: #121
> Added IMGUI_SFML_IMGUI_DEMO option to CMake build

- CMakeLists.txt
This PR combines two minor CMake improvements that are particularly useful to Windows users.
The first one activates the CMake policy [CMP0074](https://cmake.org/cmake/help/latest/policy/CMP0074.html) if it's available (CMake 3.12+). This will cause calls to `find_package()` to take into account `*_ROOT` environment variables as hints for a package's location. So instead of passing `-DIMGUI_DIR=` and `-DSFML_DIR=` on the CMake command line, one can now set the `ImGui_ROOT` and `SFML_ROOT` environment variables instead. If the policy is not set but those environment variables are found, CMake will just output a nasty policy warning on versions 3.12+.
The second change adds a debug postfix for the library. This is something that mostly developers working with the Visual Studio (MSVC) …
> Two CMake quality of life improvements

- .appveyor.yml
- .github/workflows/build.yml
- .travis.yml
Fixing #84, here is a pretty complete CI config for Windows / Linux / macOS with Visual Studio / Xcode / gcc / clang in most versions, feel free to comment or remove any system in the configs that you are not interested in. 
In every configurations the main steps are:
- Install build tools (cmake, ninja, ccache, gcc, clang, ...) depending on the config
- Install SFML dependencies (Linux only, SFML repository embed all dependencies for Windows and macOS)
- Download, configure, build, install SFML
- Download Dear ImGui
- Configure imgui-sfml
- Build imgui-sfml
Except for Visual Studio on AppVeyor, every build uses ccache and a cache system depending on the provider to keep the cache between builds, it is especially usefull for SFML as most of the source files doesn't change most of the …
> CI with Travis + AppVeyor + GitHub Actions (#84)

- imgui-SFML.cpp
- warning C4457: declaration of 'mousePos' hides function parameter
- warning C4244: 'argument': conversion from 'const T' to 'float', possible loss of data, with [ T=int ]
> Fixed 2 warnings on MSVS 16.8.2:

- cmake/FindImGui.cmake
Hello! Thank you for this amazing library!
I added a fix to the inclusion of the source file `imgui_tables.cpp` inside the `cmake/FindImGui.cmake` file. As you may know, this source file is part of the new release of Dear ImGui v1.80, but it was missing in prior releases.
For that reason, ImGui-SFML was refusing to build for versions of Dear ImGui lower than v1.80, because that specific file was missing. I just confitionally included the file in the `IMGUI_SOURCES`, depending on the version of Dear ImGui.
If you think the condition should be different (maybe a specific commit or something else), feel free to modify whatever is necessary.
> Fixed inclusion of imgui_tables.cpp source file

- README.md
The latest version of imgui requires that the imgui_tables.cpp file be included in order to use the library. I've updated the README manual install instructions to include this change.
> Update to README.md to include imgui_tables.cpp

- imgui-SFML.cpp
Always compile with warnings enabled! :)
> Fix 'bgColor' not being passed to 'ImGui::ImageButton'

- imgui-SFML.cpp
In `imconfig.h` we can enable support for more than 64k of vertices in the draw list be enabling the hash define see: https://github.com/ocornut/imgui/blob/f99fe72c42bd5d578c2443409192b139b1c6623d/imconfig.h#L96
This can be supported in this framework by making sure GL knows the correct size of the index buffer when we go to render.
> Support #define ImDrawIdx unsigned int in renderer via imconfig.h

- imgui-SFML.cpp
Hello, 
It's my first PR to this project, I don't know what is the correct procedure yet :)
During the Init process, bunch of cursors being allocated:
```
// load mouse cursors
loadMouseCursor(ImGuiMouseCursor_Arrow, sf::Cursor::Arrow);
loadMouseCursor(ImGuiMouseCursor_TextInput, sf::Cursor::Text);
loadMouseCursor(ImGuiMouseCursor_ResizeAll, sf::Cursor::SizeAll);
loadMouseCursor(ImGuiMouseCursor_ResizeNS, sf::Cursor::SizeVertical);
loadMouseCursor(ImGuiMouseCursor_ResizeEW, sf::Cursor::SizeHorizontal);
loadMouseCursor(ImGuiMouseCursor_ResizeNESW, sf::Cursor::SizeBottomLeftTopRight);
loadMouseCursor(ImGuiMouseCursor_ResizeNWSE, sf::Cursor::SizeTopLeftBottomRight);
loadMouseCursor(ImGuiMouseCursor_Hand, sf::Cursor::Hand);
```
loadMouseCursor function allocates memory for cursor and marks …
> Prevent leaking memory on cursors

- imgui-SFML.cpp
As described in https://en.sfml-dev.org/forums/index.php?topic=27180.0 and https://github.com/eliasdaler/imgui-sfml/issues/119.
`updateMouseCursor` was being spammed every tick which wasn't letting Windows temporarily override the IMGUI's cursor with the resize cursor. Other backends ([like the Win32 one](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_win32.cpp#L358)) wrap their equivalent of `updateMouseCursor` behind a dirty flag.
> Wrapping updateMouseCursor() behind a dirty flag, like other example backends. Fixes the window resize cursor not being shown.

- imgui-SFML.cpp
Whilst working on a project using the latest snapshot of SFML master branch (where the SFML v3 commits are going) I noticed that the `sf::Keyboard::Return` was no longer marked deprecated but had now been removed which caused `imgui-sfml.cpp` to fail to compile since it still relied on this enum entry. Replaced the entry with the preferred `sf::Keyboard::Enter`
> Replaced deprecated sf::Keyboard::Return with sf::Keyboard::Enter

- imconfig-SFML.h
- imgui-SFML.cpp
Hello !
Just a small update because sfml recently replaced sf::Uint8 with std::uint8_t
https://github.com/SFML/SFML/commit/e2528de20a58d56c13d22fe64fd55d701ba3c714
The CI fails with mingw errors but it is not linked to my change (only submitting an empty CL to trigger the CI leads to the exact same issue).
Thanks a lot for your work !
> Replace sf::Uint8 with std::uint8_t

- imgui-SFML.cpp
- Remove unused `NULL_JOYSTICK_BUTTON`
- Use `std::string::assign` instead of creating a temporary in `getClipboardText`
- Mark `NULL_JOYSTICK_ID` as `constexpr`
> Minor improvements

- imgui-SFML.cpp
Fixes various warnings, including: "unhandled values in switch", "implicit conversion from signed to unsigned".
> Fix some warnings

- CMakeLists.txt
As of CMake 3.27 I'm getting the following error when configuring ImGui-SFML
```
CMake Deprecation Warning at build/_deps/imgui-sfml-src/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
CMake 3.1 is VERY old at this point in the year 2023 and it's safe to assume that noboby is using a CMake version older than 3.10 or perhaps even 3.16.
> Upgrade to new enough CMake to avoid deprecation notices

- CMakeLists.txt
- imgui-SFML.cpp
Silencing the OpenGL deprecation warnings was my first goal since they were cluttering up the console output. While I was in there I added a quick a few lines to add the most basic GCC and Clang warnings. I see a few other PRs are touching on compiler warnings as well so this helps lay the groundwork to add (and fix) more warnings in the future.
I also kept another commit that fixes a little typo I found a few days ago.
> Add and fix compiler warnings

- imgui-SFML.cpp
See https://github.com/SFML/SFML/pull/2637
If we merge #249 then we can pretty easily add SFML 3 jobs to CI to continuously ensure SFML 3 support is maintained. Then as long as we run CI on a regular basis we will find these issues.
> Fix new SFML 3 build error

- CMakeLists.txt
* Following up and reverting part of https://github.com/SFML/imgui-sfml/pull/246
> Revert enabling "warnings as errors" in the default build

- CMakeLists.txt
- README.md
Draft of release notes:
<blockquote>
Support the full key range from [imgui v1.87](https://github.com/ocornut/imgui/releases/tag/v1.87), e.g. `ImGui::IsKeyDown(ImGuiKey_Q)` now works (#197)
Expanded API: Propagate boolean error state from `Texture.create` to methods such as `Init` (#191)
Expanded API: Make all joystick axes and thresholds configurable, not just the left stick (#197)
API change: Fix typo in method names: "joytick" -> "joystick" (#201)
Propagate window resize events to imgui (#222)
Fix dimming of imgui modal dialogs (004efd85a590343e8c9d166dc9d2524c199c9450)
Fix the window resize cursor not being shown on Windows (#193)
Fix memory leak from cursors (#194)
Fix for changes in imgui around `ImGuiKey` (#219)
Fix deprecations from SFML 2.5/2.6 (#187, #205)
Fix for changes in …
> ImGui-SFML 2.6 release notes

- README.md
Plus some minimal fairly-unimportant and minor tweakage  =)
> Typo fix in README: NavEnableGamepad instead of NavEnableKeyboard

- imgui-SFML.cpp
We can simplify imgui-SFML.cpp a decent amount by using the `ImVec` constructor we define in imconfig-SFML.h.
> Use conversion constructor

- imgui-SFML.cpp
SFML master has recently updated enums such as `sf::Joystick::Axis` to scoped enums, this PR is to catchup imgui-SFML master to these changes.
> Catchup imgui-SFML to scoped enum changes in SFML master

- imgui-SFML.cpp
Continuation of the work done in #270, `sf::Keyboard::Key` was recently updated to be an `enum class` on master. This PR adds a commit to keep imgui-SFML master in line with these changes.
> Catchup imgui-sfml to scoped sf::Keyboard::Key enum changes on SFML master

- imgui-SFML.h
https://github.com/SFML/SFML/pull/2766 changed `sf::Event` from a `struct` to a `class`.
> Fix forward declaration of `sf::Event`

- examples/minimal/main.cpp
- examples/multiple_windows/main.cpp
- imgui-SFML.cpp
Event inheritance was removed in SFML3. I can also split the lambda into two if that is preferred over the auto parameter.
> Fix for removed Event Inheritance

- imgui-SFML.cpp
Hello !
I just wanted to report an issue with latest ImGUI. More specifically
https://github.com/ocornut/imgui/commit/92b94980c69ff3d3d7f5dc30c1c19abfb72db47e
I do know that my current solution means older ImGUI version wouldn't work anymore so I'm wondering what would be the best solution in your opinion (Check the type of ImTextureID and assign it accordingly ? Force the type of ImTextureID to be void* ?)
Thanks in advance
> Fix ImTextureID type

- .github/workflows/ci.yml
- CMakeLists.txt
- imgui-SFML.cpp
This PR contains a migration commit to allow imgui-sfml to be compiled with the flag IMGUI_DISABLE_OBSOLETE_FUNCTIONS.
Target imgui version : 1.89
> Remove use of obsolete ImGui functions - v1.89

- imgui-SFML.cpp
This PR contains fixes for imgui 1.90 when using the IMGUI_DISABLE_OBSOLETE_FUNCTIONS flag.
Associated discussions : https://github.com/SFML/imgui-sfml/issues/301
For this PR to be finalized, the minimum supported version will have to be updated from 1.89 to 1.90.
The supported versions with the flag enabled would range from 1.90 (November 2023) to 1.91.0 (July 2024)
EDIT: It appears that the minimum version supported is unchanged, no need to update it.
To make the change on the CI settings and docs, I guess I should wait for the imgui_version branch to be merged back into the 2.6.x branch ?
PS: if several tests are implemented for different imgui targets, it could be interesting to also target the -docking tags associated with each imgui version.
(EDIT: not sure if anything could break …
> Fix for imgui 1.91.5 (clean some deprecated API calls)

- .github/workflows/ci.yml
- CMakeLists.txt
- README.md
- imgui-SFML.cpp
The members `ImGuiIO::SetClipboardTextFn` and `ImGuiIO::GetClipboardTextFn` have been obsoleted. This pull request uses the new members in `ImGuiPlatformIO`.
> Updated obsoleted functions

- CMakeLists.txt
- cmake/ImGui-SFMLConfig.cmake
Fixing a bug first reported in https://github.com/microsoft/vcpkg/issues/44123 and fixed in https://github.com/microsoft/vcpkg/pull/44203. The proper thing to do would be write install interface tests like SFML has. That would systematically prevent issues like this in the future.
> Ensure `OpenGL::GL` target is found when using config module

- imgui-SFML.cpp
Fixed SetLTriggerAxis to set the correct internal variable. See Issue #323
> Fixed SetLTriggerAxis to set the correct internal variable

- imgui-SFML.cpp
In ImGui v1.92.0 and newer, direct access to ImDrawCmd::TextureId is deprecated and replaced by the GetTexID() accessor.
> Replace direct TextureId access with GetTexID()
